export default [
    {
        id: 1,
        title: "Black alarm clock",
        description: "Keep up with the times with this neat clock",
        image: "c1.jpg",
        price: 358,
    },
    {
        id: 2,
        title: "Red alarm clock",
        description: "Keep up with the times with this neat clock",
        image: "c2.jpg",
        price: 552,
    },
    {
        id: 3,
        title: "Black alarm clock (digital)",
        description: "Keep up with the times with this neat clock",
        image: "c3.jpg",
        price: 82,
    },
    {
        id: 4,
        title: "Modern timepiece",
        description: "Keep up with the times with this neat clock",
        image: "c4.jpg",
        price: 467,
    },
    {
        id: 5,
        title: "Simple wall clock",
        description: "Keep up with the times with this neat clock",
        image: "c5.jpg",
        price: 206,
    },
    {
        id: 6,
        title: "Wooden wall clock",
        description: "Keep up with the times with this neat clock",
        image: "c6.jpg",
        price: 223,
    },
    {
        id: 7,
        title: "Modern wall clock",
        description: "Keep up with the times with this neat clock",
        image: "c7.jpg",
        price: 309,
    },
    {
        id: 8,
        title: "Roman wall clock",
        description: "Keep up with the times with this neat clock",
        image: "c8.jpg",
        price: 362,
    },
    {
        id: 9,
        title: "Golden alarm clock",
        description: "Keep up with the times with this neat clock",
        image: "c9.jpg",
        price: 54,
    },
    {
        id: 10,
        title: "Android smartwatch",
        description: "Keep up with the times with this neat clock",
        image: "sw1.jpg",
        price: 530,
    },
    {
        id: 11,
        title: "Fitness smartwatch",
        description: "Keep up with the times with this neat clock",
        image: "sw2.jpg",
        price: 350,
    },
    {
        id: 12,
        title: "Vintage wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "vw1.jpg",
        price: 194,
    },
    {
        id: 13,
        title: "Vintage wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "w1.jpg",
        price: 241,
    },
    {
        id: 14,
        title: "Digital wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "w10.jpg",
        price: 229,
    },
    {
        id: 15,
        title: "Modern wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "w11.jpg",
        price: 278,
    },
    {
        id: 16,
        title: "Modern wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "w12.jpg",
        price: 342,
    },
    {
        id: 17,
        title: "Modern wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "w13.jpg",
        price: 141,
    },
    {
        id: 18,
        title: "Modern wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "w14.jpg",
        price: 367,
    },
    {
        id: 19,
        title: "Modern wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "w2.jpg",
        price: 539,
    },
    {
        id: 20,
        title: "Date/time wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "w3.jpg",
        price: 86,
    },
    {
        id: 21,
        title: "Elegant wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "w4.jpg",
        price: 465,
    },
    {
        id: 22,
        title: "Modern wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "w5.jpg",
        price: 192,
    },
    {
        id: 23,
        title: "Fashion wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "w6.jpg",
        price: 371,
    },
    {
        id: 24,
        title: "Elegant wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "w7.jpg",
        price: 148,
    },
    {
        id: 25,
        title: "Modern wristwatch",
        description: "Keep up with the times with this neat clock",
        image: "w8.jpg",
        price: 188,
    }
]
