export default [
    {
        id: 1,
        title: "Réveil noir",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "c1.jpg",
        price: 358,
    },
    {
        id: 2,
        title: "Réveil rouge",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "c2.jpg",
        price: 552,
    },
    {
        id: 3,
        title: "Réveil noir (numérique)",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "c3.jpg",
        price: 82,
    },
    {
        id: 4,
        title: "Horloge moderne",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "c4.jpg",
        price: 467,
    },
    {
        id: 5,
        title: "Horloge murale simple",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "c5.jpg",
        price: 206,
    },
    {
        id: 6,
        title: "Horloge murale en bois",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "c6.jpg",
        price: 223,
    },
    {
        id: 7,
        title: "Horloge murale moderne",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "c7.jpg",
        price: 309,
    },
    {
        id: 8,
        title: "Horloge murale romaine",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "c8.jpg",
        price: 362,
    },
    {
        id: 9,
        title: "Réveil doré",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "c9.jpg",
        price: 54,
    },
    {
        id: 10,
        title: "Montre intelligente d'Android",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "sw1.jpg",
        price: 530,
    },
    {
        id: 11,
        title: "Montre intelligente pour l'aptitude",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "sw2.jpg",
        price: 350,
    },
    {
        id: 12,
        title: "Montre-bracelet vintage",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "vw1.jpg",
        price: 194,
    },
    {
        id: 13,
        title: "Montre-bracelet vintage",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "w1.jpg",
        price: 241,
    },
    {
        id: 14,
        title: "Montre intelligente numérique",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "w10.jpg",
        price: 229,
    },
    {
        id: 15,
        title: "Montre-bracelet moderne",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "w11.jpg",
        price: 278,
    },
    {
        id: 16,
        title: "Montre-bracelet moderne",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "w12.jpg",
        price: 342,
    },
    {
        id: 17,
        title: "Montre-bracelet moderne",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "w13.jpg",
        price: 141,
    },
    {
        id: 18,
        title: "Montre-bracelet moderne",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "w14.jpg",
        price: 367,
    },
    {
        id: 19,
        title: "Montre-bracelet moderne",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "w2.jpg",
        price: 539,
    },
    {
        id: 20,
        title: "Montre-bracelet avec date et l'heure",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "w3.jpg",
        price: 86,
    },
    {
        id: 21,
        title: "Montre-bracelet élégante",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "w4.jpg",
        price: 465,
    },
    {
        id: 22,
        title: "Montre-bracelet moderne",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "w5.jpg",
        price: 192,
    },
    {
        id: 23,
        title: "Montre-bracelet de mode",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "w6.jpg",
        price: 371,
    },
    {
        id: 24,
        title: "Montre-bracelet élégante",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "w7.jpg",
        price: 148,
    },
    {
        id: 25,
        title: "Montre-bracelet moderne",
        description: "Restez dans l'air du temps avec cette belle horloge",
        image: "w8.jpg",
        price: 188,
    }
]
