export default [
    { id: 1, image: "c1.jpg" },
    { id: 2, image: "c2.jpg" },
    { id: 3, image: "c3.jpg" },
    { id: 4, image: "c4.jpg" },
    { id: 5, image: "c5.jpg" },
    { id: 6, image: "c6.jpg" },
    { id: 7, image: "c7.jpg" },
    { id: 8, image: "c8.jpg" },
    { id: 9, image: "c9.jpg" },
    { id: 10, image: "sw1.jpg" },
    { id: 11, image: "sw2.jpg" },
    { id: 12, image: "vw1.jpg" },
    { id: 13, image: "w1.jpg" },
    { id: 14, image: "w10.jpg" },
    { id: 15, image: "w11.jpg" },
    { id: 16, image: "w12.jpg" },
    { id: 17, image: "w13.jpg" },
    { id: 18, image: "w14.jpg" },
    { id: 19, image: "w2.jpg" },
    { id: 20, image: "w3.jpg" },
    { id: 21, image: "w4.jpg" },
    { id: 22, image: "w5.jpg" },
    { id: 23, image: "w6.jpg" },
    { id: 24, image: "w7.jpg" },
    { id: 25, image: "w8.jpg" },
    { id: 26, image: "w9.jpg" }
]
